sudo: required
dist: trusty
language: node_js
node_js:
  - '6.9'

script:
  - npm install
  - ./node_modules/angular-cli/bin/ng build --prod --aot

deploy:
  provider: s3
  skip_cleanup: true
  bucket: '$ELB_BUCKET'
  region: '$ELB_REGION'
  access_key_id:
    secure: '$ELB_ACCESS_KEY_ID'
  secret_access_key:
    secure: '$ELB_SECRET_ACCESS_KEY'
