sudo: required
dist: trusty
language: node_js
node_js:
  - '6.9'

install:
  - npm install
script:
  - ./node_modules/angular-cli/bin/ng build --prod --aot

after_success:
  - npm patch minor
  - git push origin HEAD:master

deploy:
  provider: s3
  skip_cleanup: true
  bucket: '$ELB_BUCKET'
  region: '$ELB_REGION'
  local_dir: 'dist'
  access_key_id:
    secure: '$ELB_ACCESS_KEY_ID'
  secret_access_key:
    secure: '$ELB_SECRET_ACCESS_KEY'
